# PCA , SVD , LDA on Breast Cancer Dataset

In [40]:
import pandas as pd 
import numpy as np
data = pd.read_csv(r"C:\Users\B V N DURGA VINAY\Downloads\brca.csv")
print(data)

     mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     diagnosis  
0            0  
1            0  
2           

In [41]:
data.isna().sum()

mean_radius        0
mean_texture       0
mean_perimeter     0
mean_area          0
mean_smoothness    0
diagnosis          0
dtype: int64

# Standardizing the data

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
sc = scaler.fit_transform(data)
print(sc)

[[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633 -1.29767572]
 [ 1.82982061 -0.35363241  1.68595471  1.90870825 -0.82696245 -1.29767572]
 [ 1.57988811  0.45618695  1.56650313  1.55888363  0.94221044 -1.29767572]
 ...
 [ 0.70228425  2.0455738   0.67267578  0.57795264 -0.84048388 -1.29767572]
 [ 1.83834103  2.33645719  1.98252415  1.73521799  1.52576706 -1.29767572]
 [-1.80840125  1.22179204 -1.81438851 -1.34778924 -3.11208479  0.77060855]]


In [43]:
x = data.drop('diagnosis',axis=1)
y = data['diagnosis']
print(x.shape)
print(y.shape)

(569, 5)
(569,)


# Splitting the dataset into the Training set and Test set

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)

# Building a Logistic Regression model

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import cohen_kappa_score
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
spec = cm[0][0]/(cm[0][0]+cm[0][1])
print('accuracy score :-',accuracy_score(y_test,y_pred))
print('recall score :-',recall_score(y_test,y_pred,average="micro"))
print('specification:- ',spec)
print('precision score:-',precision_score(y_test,y_pred,average="micro"))
print('f1 score:-',f1_score(y_test,y_pred,average="micro"))
print('kappa score:-',cohen_kappa_score(y_test,y_pred))

accuracy score :- 0.8947368421052632
recall score :- 0.8947368421052632
specification:-  0.8181818181818182
precision score:- 0.8947368421052632
f1 score:- 0.8947368421052632
kappa score:- 0.774108322324967


C:\Users\B V N DURGA VINAY\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# PCA

In [46]:
from sklearn.decomposition import PCA
pca = PCA(0.95)

In [47]:
x_pca = pca.fit_transform(x)
x_pca_df=pd.DataFrame(x_pca)

In [48]:
explained_variance_ratio = pca.explained_variance_ratio_
print("Explained Variance Ratio:\n", explained_variance_ratio)

Explained Variance Ratio:
 [0.99973765]


In [49]:
final_data = pd.concat([x_pca_df, y], axis=1)
final_data

0  diagnosis
0    347.389677          0
1    672.360684          0
2    549.459884          0
3   -269.152801          0
4    643.562702          0
..          ...        ...
564  825.644608          0
565  607.435811          0
566  203.898289          0
567  612.040081          0
568 -475.802609          1

[569 rows x 2 columns]

In [50]:
xf=final_data.iloc[:,:-1]
xf
yf=final_data.iloc[:,-1]
yf
x_train,x_test,y_train,y_test=train_test_split(xf,yf,test_size=0.2,random_state=0)
x_train

0
338 -345.194200
427 -295.887994
406  145.607744
96  -204.294942
490 -188.886209
..          ...
277  448.066994
9   -179.106626
359 -377.632846
192 -368.091092
559 -251.987195

[455 rows x 1 columns]

In [51]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
spec = cm[0][0]/(cm[0][0]+cm[0][1])
print('accuracy score :-',accuracy_score(y_test,y_pred))
print('recall score :-',recall_score(y_test,y_pred,average="micro"))
print('specification:- ',spec)
print('precision score:-',precision_score(y_test,y_pred,average="micro"))
print('f1 score:-',f1_score(y_test,y_pred,average="micro"))
print('kappa score:-',cohen_kappa_score(y_test,y_pred))

accuracy score :- 0.8947368421052632
recall score :- 0.8947368421052632
specification:-  0.8297872340425532
precision score:- 0.8947368421052632
f1 score:- 0.8947368421052632
kappa score:- 0.7799935670633644


# SVD

In [52]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(4)

In [53]:
x_svd = svd.fit_transform(x)
x_train_svd,x_test_svd,y_train,y_test = train_test_split(x_svd,yf,test_size=0.2,random_state=30)

In [54]:
model.fit(x_train_svd,y_train)
y_svd_pred = model.predict(x_test_svd)

In [55]:
cm = confusion_matrix(y_test,y_pred)
spec = cm[0][0]/cm[0][0]+cm[0][1]
print('accuracy score :-',accuracy_score(y_test,y_svd_pred))
print('recall score :-',recall_score(y_test,y_svd_pred,average="micro"))
print('specification:- ',spec)
print('precision score:-',precision_score(y_test,y_svd_pred,average="micro"))
print('f1 score:-',f1_score(y_test,y_svd_pred,average="micro"))
print('kappa score:-',cohen_kappa_score(y_test,y_svd_pred))

accuracy score :- 0.8771929824561403
recall score :- 0.8771929824561403
specification:-  28.0
precision score:- 0.8771929824561403
f1 score:- 0.8771929824561403
kappa score:- 0.7387033398821219


# LDA

In [56]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
n_classes = len(np.unique(y))
n_components = min(19, n_classes - 1, x.shape[1])
lda = LinearDiscriminantAnalysis(n_components=n_components)

In [57]:
x_lda = lda.fit_transform(x,y)
x_train_lda,x_test_lda,y_train,y_test = train_test_split(x_lda,y,test_size=0.2,random_state=0)

In [58]:
model.fit(x_train_lda,y_train)
y_pred_lda = model.predict(x_test_lda)

In [59]:
cm = confusion_matrix(y_test,y_pred)
spec = cm[0][0]/(cm[0][0]+cm[0][1])
print('accuracy score :-',accuracy_score(y_test,y_pred_lda))
print('recall score :-',recall_score(y_test,y_pred_lda,average="micro"))
print('specification:- ',spec)
print('precision score:-',precision_score(y_test,y_pred_lda,average="micro"))
print('f1 score:-',f1_score(y_test,y_pred_lda,average="micro"))
print('kappa score:-',cohen_kappa_score(y_test,y_pred_lda))

accuracy score :- 0.9122807017543859
recall score :- 0.9122807017543859
specification:-  0.8297872340425532
precision score:- 0.9122807017543859
f1 score:- 0.9122807017543859
kappa score:- 0.8201325339223731
